version: "3.8"

services:
  semgrep:
    image: returntocorp/semgrep:latest
    container_name: semgrep
    working_dir: /src
    volumes:
      - .:/src
    command: >
      semgrep
      --config p/owasp-top-ten
      --json
      --output /src/semgrep-results.json
