version: "3.8"

services:
  semgrep:
    image: returntocorp/semgrep:latest
    container_name: semgrep
    working_dir: /src
    volumes:
      - .:/src
    command: >
      semgrep
      --config p/owasp-top-ten
      --json
      --output /src/semgrep-results.json

  trivy:
    image: aquasec/trivy:latest
    container_name: trivy
    volumes:
      - .:/project
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /project
    command: >
      image -f json  -o /project/trivy-image-results.json bwa:2

  snyk-docker:
    image: snyk/snyk:docker
    container_name: snyk-docker
    environment:
      - SNYK_TOKEN=${SNYK_TOKEN}
    working_dir: /project
    volumes:
      - .:/project
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      snyk test --json-file-output=/project/snyk-image-results.json --docker bwa:2

  snyk-test:
    image: snyk/snyk:docker
    container_name: snyk-test
    environment:
      - SNYK_TOKEN=${SNYK_TOKEN}
    volumes:
      - .:/project
    command: >
      snyk test --file=/project/BrokenWebAPI.sln --json-file-output=/project/snyk-test-results.json

  snyk-code:
    image: snyk/snyk:docker
    container_name: snyk-code
    environment:
      - SNYK_TOKEN=${SNYK_TOKEN}
    volumes:
      - .:/project
    command: >
      snyk code test --file=/project/BrokenWebAPI.sln --json-file-output=/project/snyk-code-test-results.json

  zap:
    image: zaproxy/zap-stable
    container_name: zap
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 4G
    command: >
      zap-full-scan.py
      -t http://localhost:5000
      -z "context.include=http://localhost:5000/api/.*"
      -z "spider.maxDuration=5"
      -J zap-fullscan-report.json
      -r zap-report.html
    volumes:
      - ./zap-reports:/zap/wrk
